{
 "title": "Blocky query",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client_name",
    "label": "Client name",
    "query": "select distinct client_name from log_entries"
   },
   {
    "name": "response_type",
    "label": "Response type",
    "query": "select distinct response_type from log_entries"
   }
  ]
 },
 "panels": [
  {
   "title": "Query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(t.request_Ts) as time,\n  t.duration_ms\nFROM log_entries t\nWHERE\n  $__timeFilter(t.request_Ts) and t.response_type in ($response_type) and ($client_name = '*' or t.client_name = $client_name)\nORDER BY request_ts"
    }
   ]
  },
  {
   "title": "Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as value from log_entries t WHERE $__timeFilter(t.request_Ts) and t.response_type in ($response_type) and ($client_name = '*' or t.client_name = $client_name)"
    }
   ]
  },
  {
   "title": "Top 20 queried domains",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT t.question_name as metric, count(*) as value from log_entries t WHERE $__timeFilter(t.request_Ts) and t.response_type in ($response_type) and ($client_name = '*' or t.client_name = $client_name) group by t.question_name order by count(*) desc limit 20"
    }
   ]
  },
  {
   "title": "Last queries",
   "type": "table",
   "description": "Last queries, newest on top",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(t.request_Ts) as \"time\", t.client_ip as \"client IP\", t.client_name as \"client name\", t.duration_ms as \"duration in ms\", t.response_type as \"response type\", t.question_type as \"question type\", t.question_name as \"question name\", t.answer as \"answer\" from log_entries t WHERE $__timeFilter(t.request_Ts) and t.response_type in ($response_type) and ($client_name = '*' or t.client_name = $client_name) order by t.request_Ts desc limit 100"
    }
   ]
  }
 ]
}